{% set name = "gruut-ipa" %}
{% set version = "0.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gruut-ipa-{{ version }}.tar.gz
  sha256: 564e2e77d3076b66294845d14db452dd44ff258431f38c415696819949948bc7

build:
  number: 0
  noarch: python
  entry_points:
    - gruut-ipa = gruut_ipa.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - gruut_ipa
    - tests
  commands:
    - pip check
    - gruut-ipa --help
  requires:
    - pip

about:
  home: https://github.com/rhasspy/gruut-ipa
  summary: Library for manipulating pronunciations using the International Phonetic Alphabet (IPA)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
