{% set name = "gruut-ipa" %}
{% set version = "0.13.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gruut-ipa-{{ version }}.tar.gz
  sha256: 71776eb99f46e119ab14d3d4e536f54317133607cc2f6bad9711ab51f1bec66e

build:
  number: 1
  noarch: python
  entry_points:
    - gruut-ipa = gruut_ipa.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - gruut_ipa
    - tests
  commands:
    - pip check
    - gruut-ipa --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rhasspy/gruut-ipa
  summary: Library for manipulating pronunciations using the International Phonetic Alphabet (IPA)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
